/*
 * DIO_IC_PINS_config.h
 *
 *  Created on: Dec 30, 2021
 *      Author: Mega Store
 */

#ifndef DIO_IC_PINS_CONFIG_H_
#define DIO_IC_PINS_CONFIG_H_

#define PORTA_PIN0	0
#define PORTA_PIN1	1
#define PORTA_PIN2	2
#define PORTA_PIN3	3
#define PORTA_PIN4	4
#define PORTA_PIN5	5
#define PORTA_PIN6	6
#define PORTA_PIN7	7

#define PORTB_PIN0	8
#define PORTB_PIN1	9
#define PORTB_PIN2	10
#define PORTB_PIN3	11
#define PORTB_PIN4	12
#define PORTB_PIN5	13
#define PORTB_PIN6	14
#define PORTB_PIN7	15

#define PORTC_PIN0	16
#define PORTC_PIN1	17
#define PORTC_PIN2	18
#define PORTC_PIN3	19
#define PORTC_PIN4	20
#define PORTC_PIN5	21
#define PORTC_PIN6	22
#define PORTC_PIN7	23

#define PORTD_PIN0	24
#define PORTD_PIN1	25
#define PORTD_PIN2	26
#define PORTD_PIN3	27
#define PORTD_PIN4	28
#define PORTD_PIN5	29
#define PORTD_PIN6	30
#define PORTD_PIN7	31

#define LEFT_CHECK_PINS  {PORTA_PIN0, PORTA_PIN1, PORTA_PIN2, PORTA_PIN3, PORTA_PIN4, PORTA_PIN5, PORTA_PIN6, PORTA_PIN7, PORTD_PIN4, PORTD_PIN5, PORTD_PIN6, PORTD_PIN7}
#define RIGHT_CHECK_PINS {PORTC_PIN0, PORTC_PIN1, PORTC_PIN2, PORTC_PIN3, PORTC_PIN4, PORTC_PIN5, PORTC_PIN6, PORTC_PIN7, PORTB_PIN0, PORTB_PIN1, PORTB_PIN2, PORTB_PIN3}

#endif /* DIO_IC_PINS_CONFIG_H_ */
